module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Material Design 3 - TelecomPro Color System
        "primary": "#070235",
        "on-primary": "#ffffff",
        "primary-container": "#1e1b4b",
        "on-primary-container": "#8683ba",
        "secondary": "#4648d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#6063ee",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary": "#080c0d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1f2224",
        "on-tertiary-container": "#86898b",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fcf8fd",
        "on-background": "#1c1b1f",
        "surface": "#fcf8fd",
        "on-surface": "#1c1b1f",
        "surface-dim": "#dcd9de",
        "surface-bright": "#fcf8fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "surface-container": "#f1ecf2",
        "surface-container-high": "#ebe7ec",
        "surface-container-highest": "#e5e1e6",
        "on-surface-variant": "#47464f",
        "outline": "#787680",
        "outline-variant": "#c8c5d0",
        "inverse-surface": "#313034",
        "inverse-on-surface": "#f3eff4",
        "inverse-primary": "#c4c1fb",
        "surface-tint": "#5b598c",
        "primary-fixed-dim": "#c4c1fb",
        "primary-fixed": "#e3dfff",
        "on-primary-fixed": "#181445",
        "on-primary-fixed-variant": "#444173",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "gutter": "1.5rem",
        "stack-md": "1rem",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem",
        "container-max": "1440px",
        "stack-lg": "2rem",
      },
      fontFamily: {
        "body": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
